Fix for broken GSI documentation
couchbasecloud/terraform-provider-couchbase-capella pull request #248
Opened 2024-12-13 05:09 UTC by a-atri

## Jira

* AV-92771

## Description

Please include a summary of the fix/feature/change, including any relevant motivation and context.

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue). Please, add the "bug" label to the PR.
- [ ] New feature (non-breaking change which adds functionality). Please, add the "enhancement" label to the PR.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected). Please, add the "breaking change" label to the PR.
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Manual Testing Approach

### How was this change tested and do you have evidence? _**(REQUIRED: Select at least 1)**_

- [ ] Manually tested
- [ ] Unit tested
- [ ] Acceptance tested
- [ ] Unable to test / will not test (Please provide comments in section below)

### Testing

<details open>
  <summary>Testing</summary>
  
</details>

## Required Checklist:

- [ ] I have checked that this change does not generate any credentials and that **they are NOT accidentally logged anywhere**.
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if required)
- [ ] I have run make fmt and formatted my code
- [ ] I have made sure that no schema field is marked with both requiresReplace and computed
## Further comments

2024-12-13 06:22 UTC, SaicharanCB submitted a review, later dismissed

2024-12-13 09:52 UTC, PaulomeeCb approved these changes
lgtm 👍 , would request review from @l0n3star for cross-checking GSI.

2024-12-13 21:36 UTC, Rebecca-Martinez007 requested changes
Made a few changes to the phrasing and wording. 

@simon-dew let me know if there any other changes you want to make.

2024-12-13 21:36 UTC, Rebecca-Martinez007 commented on docs/resources/cluster.md
> +- `disk` (Attributes) The 'storage' and 'IOPS' fields are required for AWS. For Azure, only the 'disktype' field is required, and for Ultra disk type, you can provide all 3 - storage, iops and autoex
```suggestion
- `disk` (Attributes) For AWS, the 'storage' and 'IOPS' fields are required. For Azure, only the 'disktype' field is required. For Ultra disk type, you can provide all 3 fields: 'storage', 'IOPS' and 'auto-expansion'. For Premium type, you can set the 'auto-expansion' field only. For GCP, only the 'pd ssd' disk type is available, and you cannot set the 'IOPS' field. (See [below for nested schema](#nestedatt--service_groups--node--disk))
```

2024-12-16 11:35 UTC, simon-dew submitted a review, later dismissed
LGTM 👍

2024-12-16 13:32 UTC, Rebecca-Martinez007 approved these changes
LGTM!

2024-12-16 13:49 UTC, SaicharanCB approved these changes

2024-12-18 15:52 UTC, Rebecca-Martinez007 approved these changes
LGTM

2024-12-19 07:24 UTC, PaulomeeCb approved these changes

2024-12-19 07:27 UTC, merged